### ISSUE TITLE
Dosent work

### ISSUE THREAD

**Issue by Chokerino** [ericmjl/protein-interaction-network#173] opened 2020-08-18 14:11 UTC
`p = ProteinGraph('4u0g.pdb')`

gives an error

`AttributeError: 'ProteinGraph' object has no attribute 'node'`

**Comment by ericmjl** [comment] 2020-08-18 16:39
Hi @Chokerino! Thanks for pinging in. Can you paste the full stack trace please? That’ll help me narrow down the offending line in the codebase.

**Comment by Chokerino** [comment] 2020-08-18 16:51
`p = ProteinGraph('4u0g.pdb')
  File "C:\Python\lib\site-packages\proteingraph\pin.py", line 61, in __init__
    self.compute_interaction_graph()
  File "C:\Python\lib\site-packages\proteingraph\pin.py", line 174, in compute_interaction_graph
    v()
  File "C:\Python\lib\site-packages\proteingraph\pin.py", line 422, in add_ionic_interactions_
    self.node[r1]["resi_name"] in POS_AA
AttributeError: 'ProteinGraph' object has no attribute 'node'`

**Comment by ericmjl** [comment] 2020-08-19 16:13
@Chokerino I think I know what the problem is. I must have forgotten to cut a release. Can you install from source and see whether that fixes the error?

```
pip install git+https://github.com/ericmjl/protein-interaction-network.git
```

**Comment by Chokerino** [comment] 2020-08-19 19:47
It works now. Did you actually use this library to work on GNN's? If so is there any repo I can consult. Or are you aware of any other libraries which can give an accurate graph representation of proteins.

**Comment by ericmjl** [comment] 2020-08-20 00:53
I've used it before, but never published the work. There's another library you can consult, it's referenced on the README of the repo (get_contacts, I think).

**Comment by ericmjl** [comment] 2020-09-05 20:01
New release cut now! Going to close this issue. Feel free to open a new issue if needed!

**Closed by ericmjl** 2020-09-05 20:01 UTC
